version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: canteen-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_strong_password
      - POSTGRES_DB=postgres
